/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as TasksTaskIdEditRouteImport } from './routes/tasks.$taskId.edit'
import { Route as ApiPublicFacebookCallbackRouteImport } from './routes/api/public/facebook.callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdEditRoute = TasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFacebookCallbackRoute =
  ApiPublicFacebookCallbackRouteImport.update({
    id: '/api/public/facebook/callback',
    path: '/api/public/facebook/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/api/public/facebook/callback': typeof ApiPublicFacebookCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/api/public/facebook/callback': typeof ApiPublicFacebookCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$taskId/edit': typeof TasksTaskIdEditRoute
  '/api/public/facebook/callback': typeof ApiPublicFacebookCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/tasks/new'
    | '/tasks/$taskId/edit'
    | '/api/public/facebook/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/tasks/new'
    | '/tasks/$taskId/edit'
    | '/api/public/facebook/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/tasks/new'
    | '/tasks/$taskId/edit'
    | '/api/public/facebook/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TasksNewRoute: typeof TasksNewRoute
  TasksTaskIdEditRoute: typeof TasksTaskIdEditRoute
  ApiPublicFacebookCallbackRoute: typeof ApiPublicFacebookCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/edit': {
      id: '/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof TasksTaskIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/facebook/callback': {
      id: '/api/public/facebook/callback'
      path: '/api/public/facebook/callback'
      fullPath: '/api/public/facebook/callback'
      preLoaderRoute: typeof ApiPublicFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TasksNewRoute: TasksNewRoute,
  TasksTaskIdEditRoute: TasksTaskIdEditRoute,
  ApiPublicFacebookCallbackRoute: ApiPublicFacebookCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
